import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar/NavBar";

const font = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
